
language: ruby

rvm:
  #- 1.8.7 # no, since it doesn't get fun(a, *b, c)
  #- 1.9.3
  #- 2.1.1
  - 2.2.2
  - 2.4.2
  - 2.5.1
  #- jruby-18mode
  #- jruby-19mode
  #- jruby-20mode
  #- jruby-9.1.13.0
  #
  #- jruby-9.2.5.0

#matrix:
#  include:
#    - rvm: jruby-9.1.13.0
#    #- env: JRUBY_OPTS="--profile.api"

#before_install: gem install bundler
script: bundle exec rspec
branches:
  only:
    - master
  #except:
  #  - master

sudo: false
cache: bundler

addons:
  apt:
    packages:
    - qpdf

